services:
    sqlscript:
        image: jekkos/opensourcepos:sql-master
        command: /bin/sh -c 'exit 0'
        
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: ospos
            MYSQL_USER: admin
            MYSQL_PASSWORD: 7J?LQK:2J:Yj
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_net

    ospos:
        build: 
            context: .
            target: ospos_dev 
            args:
                - USERID=1000
                - GROUPID=1000
        restart: always
        depends_on:
            - mysql
        ports:
            - "8088:80"
        networks:
            - app_net
        volumes:
            - .:/app 
            - uploads:/app/writable/uploads
            - logs:/app/writable/logs
            - cache:/app/writable/cache
        environment:
            - CI_ENVIRONMENT=development
            - FORCE_HTTPS=false
            - PHP_TIMEZONE=UTC
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=7J?LQK:2J:Yj
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql

# --- ADD THIS NEW PHPMYADMIN SECTION ---
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=mysql
        networks:
            - app_net
        depends_on:
            - mysql
    # ---------------------------------------
networks:
    app_net:

volumes:
    db_data:
    uploads:
    logs:
    cache:

